services:
  redis:
      image: redis:7
      container_name: redis
      ports:
        - "6389:6379"
      healthcheck:
       test: ["CMD", "redis-cli", "ping"]
       interval: 10s
       retries: 5
       start_period: 30s
       timeout: 10s
  joura-pothole-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    env_file:
      - .env
    volumes:
      - joura-pothole-logs:/app/winston
      - /app/node_modules
      - .:/app    
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped  
volumes:
  joura-pothole-logs:
    
