services:
  redis:
      image: redis:7
      container_name: redis
      ports:
        - "6379:6379"
  joura-pothole-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    env_file:
      - .env
    volumes:
      - joura-pothole-logs:/app/winston
      - /app/node_modules
      - .:/app    
    depends_on:
      - redis
    restart: unless-stopped  

  

volumes:
  joura-pothole-logs:
    